window.PAINEL_DATA = {
  "gerado_em": "2026-08-13T17:19:05+00:00",
  "periods": [
    "today",
    "yesterday",
    "last_7d",
    "last_14d",
    "last_30d",
    "this_month",
    "last_month",
    "maximum"
  ],
  "marcos": [
    {
      "cliente": "Bruna Susanne",
      "data": "2026-08-02",
      "titulo": "juros: ler SEMPRE em janela de 7 ou 28 dias",
      "efeito": "Medido nos mesmos R$ 917 de julho: janela de 1 dia mostra 1 venda (R$ 1.500), 7 dias mostra 6 (R$ 9.247), 28 dias mostra 7 (R$ 15.247). Só 1 das 7 vendas fecha em 24h do clique — o ciclo do revisional é longo. O número que aparece por padrão SUBCONTA a linha de juros. Ao relatar venda de juros, declarar a janela."
    },
    {
      "cliente": "Bruna Susanne",
      "data": "2026-07-21",
      "titulo": "Dualhook (coexistência do WhatsApp) entrou no ar",
      "efeito": "Só a partir daqui a Meta e o nosso webhook enxergam as mensagens trocadas. Antes desta data, conversa realizada e profundidade não eram ZERO — eram CEGAS. NÃO comparar leads/conversas antes × depois: a diferença é de medição, não de desempenho. Vale também para julgar criativo: quem rodou antes de 21/07 pode ter gerado conversa e venda sem registro (ex.: 'Quanto da parcela abate a dívida')."
    }
  ],
  "nota": "faturamento = caixa do cliente (não atribuído ≤7d); Bruna = receita esperada em caso de ganho; INICIADAS = quem começou a conversa (webhook onde cobre, senão Meta); REALIZADAS = trocou ≥N msgs (nosso webhook), na janela coberta — 'sem captura' antes do webhook ligar.",
  "accounts": [
    {
      "client": "Paola Bones",
      "label": "Estúdio Paola Bones",
      "currency": "BRL",
      "consulta_label": null,
      "receita_esperada": false,
      "vendas_dia": {},
      "periods": {
        "today": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "yesterday": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_7d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_14d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_30d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "this_month": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_month": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "maximum": {
          "gasto": 32716.46,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 18797,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        }
      }
    },
    {
      "client": "Marcelle Lima",
      "label": "Marcelle Lima | Esteticista",
      "currency": "BRL",
      "consulta_label": null,
      "receita_esperada": false,
      "vendas_dia": {},
      "periods": {
        "today": {
          "gasto": 56.16,
          "conversas": 0,
          "conversas_fonte": "real",
          "leads": 1,
          "cliques": 10,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 1,
          "iniciadas_fonte": "real",
          "realizadas": 0,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 0,
          "clid_pct": 0.0
        },
        "yesterday": {
          "gasto": 110.21,
          "conversas": 2,
          "conversas_fonte": "real",
          "leads": 1,
          "cliques": 33,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 55.1,
          "folga": null,
          "iniciadas": 3,
          "iniciadas_fonte": "real",
          "realizadas": 2,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 1,
          "clid_pct": 33.3
        },
        "last_7d": {
          "gasto": 222.94,
          "conversas": 8,
          "conversas_fonte": "real",
          "leads": 3,
          "cliques": 64,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 27.87,
          "folga": null,
          "iniciadas": 11,
          "iniciadas_fonte": "real",
          "realizadas": 8,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 3,
          "clid_pct": 27.3
        },
        "last_14d": {
          "gasto": 222.94,
          "conversas": 11,
          "conversas_fonte": "real",
          "leads": 3,
          "cliques": 64,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 20.27,
          "folga": null,
          "iniciadas": 15,
          "iniciadas_fonte": "real",
          "realizadas": 11,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 3,
          "clid_pct": 20.0
        },
        "last_30d": {
          "gasto": 1028.96,
          "conversas": 42,
          "conversas_fonte": "real",
          "leads": 50,
          "cliques": 236,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 24.5,
          "folga": null,
          "iniciadas": 69,
          "iniciadas_fonte": "real",
          "realizadas": 42,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 29,
          "clid_pct": 42.0
        },
        "this_month": {
          "gasto": 279.1,
          "conversas": 10,
          "conversas_fonte": "real",
          "leads": 4,
          "cliques": 74,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 27.91,
          "folga": null,
          "iniciadas": 14,
          "iniciadas_fonte": "real",
          "realizadas": 10,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 3,
          "clid_pct": 21.4
        },
        "last_month": {
          "gasto": 1045.29,
          "conversas": 42,
          "conversas_fonte": "real",
          "leads": 55,
          "cliques": 543,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 24.89,
          "folga": null,
          "iniciadas": 80,
          "iniciadas_fonte": "real",
          "realizadas": 42,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 35,
          "clid_pct": 43.8
        },
        "maximum": {
          "gasto": 12709.97,
          "conversas": 100,
          "conversas_fonte": "real",
          "leads": 353,
          "cliques": 7859,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 25.44,
          "folga": null,
          "gasto_janela": 2543.99,
          "iniciadas": 174,
          "iniciadas_fonte": "real",
          "realizadas": 100,
          "realizadas_fonte": "real",
          "janela_desde": "2026-06-05",
          "com_clid": 84,
          "clid_pct": 48.3
        }
      },
      "captura": {
        "desde": "2026-06-05",
        "contatos": 174,
        "com_clid": 84,
        "clid_pct": 48.3
      }
    },
    {
      "client": "Sofia Scherer",
      "label": "Sofia Scherer | Biomédica",
      "currency": "BRL",
      "consulta_label": "Avaliação",
      "receita_esperada": false,
      "vendas_dia": {
        "2026-05-30": {
          "c": 0,
          "v": 2,
          "f": 3940.0
        },
        "2026-07-13": {
          "c": 4,
          "v": 0,
          "f": 0.0
        },
        "2026-07-23": {
          "c": 2,
          "v": 0,
          "f": 0.0
        },
        "2026-07-30": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-08-01": {
          "c": 0,
          "v": 1,
          "f": 4590.0
        },
        "2026-07-31": {
          "c": 0,
          "v": 2,
          "f": 2500.0
        }
      },
      "periods": {
        "today": {
          "gasto": 19.3,
          "conversas": 0,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 2,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 1,
          "iniciadas_fonte": "real",
          "realizadas": 0,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 0,
          "clid_pct": 0.0
        },
        "yesterday": {
          "gasto": 15.32,
          "conversas": 0,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 4,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "real",
          "realizadas": 0,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 0,
          "clid_pct": null
        },
        "last_7d": {
          "gasto": 260.47,
          "conversas": 2,
          "conversas_fonte": "real",
          "leads": 1,
          "cliques": 71,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 130.24,
          "folga": null,
          "iniciadas": 7,
          "iniciadas_fonte": "real",
          "realizadas": 2,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 1,
          "clid_pct": 14.3
        },
        "last_14d": {
          "gasto": 580.66,
          "conversas": 5,
          "conversas_fonte": "real",
          "leads": 1,
          "cliques": 257,
          "vendas": 3,
          "faturamento": 7090.0,
          "consultas": 1,
          "ticket": 2363.33,
          "custo_venda": 193.55,
          "lucro": 6509.34,
          "margem_pct": 91.8,
          "roas_conta": 12.21,
          "consultas_por_venda": 0.33,
          "taxa_conversao_pct": 300.0,
          "teto_conversa": 1418.0,
          "custo_conversa": 116.13,
          "folga": 12.21,
          "iniciadas": 15,
          "iniciadas_fonte": "real",
          "realizadas": 5,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 1,
          "clid_pct": 6.7
        },
        "last_30d": {
          "gasto": 1279.6,
          "conversas": 24,
          "conversas_fonte": "real",
          "leads": 10,
          "cliques": 621,
          "vendas": 3,
          "faturamento": 7090.0,
          "consultas": 3,
          "ticket": 2363.33,
          "custo_venda": 426.53,
          "lucro": 5810.4,
          "margem_pct": 82.0,
          "roas_conta": 5.54,
          "consultas_por_venda": 1.0,
          "taxa_conversao_pct": 100.0,
          "teto_conversa": 295.42,
          "custo_conversa": 53.32,
          "folga": 5.54,
          "iniciadas": 44,
          "iniciadas_fonte": "real",
          "realizadas": 24,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 9,
          "clid_pct": 20.5
        },
        "this_month": {
          "gasto": 518.26,
          "conversas": 3,
          "conversas_fonte": "real",
          "leads": 1,
          "cliques": 211,
          "vendas": 1,
          "faturamento": 4590.0,
          "consultas": 0,
          "ticket": 4590.0,
          "custo_venda": 518.26,
          "lucro": 4071.74,
          "margem_pct": 88.7,
          "roas_conta": 8.86,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 1530.0,
          "custo_conversa": 172.75,
          "folga": 8.86,
          "iniciadas": 13,
          "iniciadas_fonte": "real",
          "realizadas": 3,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 1,
          "clid_pct": 7.7
        },
        "last_month": {
          "gasto": 1162.73,
          "conversas": 41,
          "conversas_fonte": "real",
          "leads": 23,
          "cliques": 658,
          "vendas": 2,
          "faturamento": 2500.0,
          "consultas": 7,
          "ticket": 1250.0,
          "custo_venda": 581.37,
          "lucro": 1337.27,
          "margem_pct": 53.5,
          "roas_conta": 2.15,
          "consultas_por_venda": 3.5,
          "taxa_conversao_pct": 28.6,
          "teto_conversa": 56.2,
          "custo_conversa": 26.14,
          "folga": 2.15,
          "gasto_janela": 1071.77,
          "iniciadas": 64,
          "iniciadas_fonte": "real",
          "realizadas": 41,
          "realizadas_fonte": "real",
          "janela_desde": "2026-07-04",
          "com_clid": 20,
          "clid_pct": 31.2
        },
        "maximum": {
          "gasto": 7535.4,
          "conversas": 44,
          "conversas_fonte": "real",
          "leads": 39,
          "cliques": 10675,
          "vendas": 5,
          "faturamento": 11030.0,
          "consultas": 7,
          "ticket": 2206.0,
          "custo_venda": 1507.08,
          "lucro": 3494.6,
          "margem_pct": 31.7,
          "roas_conta": 1.46,
          "consultas_por_venda": 1.4,
          "taxa_conversao_pct": 71.4,
          "teto_conversa": 52.76,
          "custo_conversa": 36.14,
          "folga": 1.46,
          "gasto_janela": 1590.03,
          "iniciadas": 77,
          "iniciadas_fonte": "real",
          "realizadas": 44,
          "realizadas_fonte": "real",
          "janela_desde": "2026-07-04",
          "com_clid": 21,
          "clid_pct": 27.3
        }
      },
      "captura": {
        "desde": "2026-07-04",
        "contatos": 77,
        "com_clid": 21,
        "clid_pct": 27.3
      }
    },
    {
      "client": "Studio NL",
      "label": "Natalia Lazzarotto Arq.",
      "currency": "BRL",
      "consulta_label": "Reunião",
      "receita_esperada": false,
      "vendas_dia": {
        "2026-04-22": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-04-21": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-04-14": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-04-06": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-03-24": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-05-06": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-02-25": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-05-11": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-05-15": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-05-30": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-06-11": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-06-09": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-06-04": {
          "c": 0,
          "v": 1,
          "f": 15000.0
        },
        "2025-11-01": {
          "c": 0,
          "v": 1,
          "f": 22000.0
        },
        "2026-01-01": {
          "c": 0,
          "v": 2,
          "f": 70200.0
        },
        "2026-03-01": {
          "c": 0,
          "v": 1,
          "f": 25184.0
        },
        "2026-07-01": {
          "c": 2,
          "v": 0,
          "f": 0.0
        },
        "2026-07-06": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-08-07": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-08-04": {
          "c": 2,
          "v": 0,
          "f": 0.0
        },
        "2026-08-06": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-08-03": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-08-05": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-07-24": {
          "c": 0,
          "v": 1,
          "f": 43040.0
        },
        "2026-07-08": {
          "c": 1,
          "v": 0,
          "f": 0.0
        }
      },
      "periods": {
        "today": {
          "gasto": 32.71,
          "conversas": 0,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 18,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "real",
          "realizadas": 0,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 0,
          "clid_pct": null
        },
        "yesterday": {
          "gasto": 76.73,
          "conversas": 0,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 40,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 1,
          "iniciadas_fonte": "real",
          "realizadas": 0,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 0,
          "clid_pct": 0.0
        },
        "last_7d": {
          "gasto": 416.74,
          "conversas": 2,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 275,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 2,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": 0.0,
          "teto_conversa": 0.0,
          "custo_conversa": 208.37,
          "folga": null,
          "iniciadas": 7,
          "iniciadas_fonte": "real",
          "realizadas": 2,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 1,
          "clid_pct": 14.3
        },
        "last_14d": {
          "gasto": 836.78,
          "conversas": 8,
          "conversas_fonte": "real",
          "leads": 2,
          "cliques": 552,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 6,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": 0.0,
          "teto_conversa": 0.0,
          "custo_conversa": 104.6,
          "folga": null,
          "iniciadas": 17,
          "iniciadas_fonte": "real",
          "realizadas": 8,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 3,
          "clid_pct": 17.6
        },
        "last_30d": {
          "gasto": 1881.75,
          "conversas": 15,
          "conversas_fonte": "real",
          "leads": 2,
          "cliques": 1523,
          "vendas": 1,
          "faturamento": 43040.0,
          "consultas": 6,
          "ticket": 43040.0,
          "custo_venda": 1881.75,
          "lucro": 41158.25,
          "margem_pct": 95.6,
          "roas_conta": 22.87,
          "consultas_por_venda": 6.0,
          "taxa_conversao_pct": 16.7,
          "teto_conversa": 2869.33,
          "custo_conversa": 125.45,
          "folga": 22.87,
          "iniciadas": 47,
          "iniciadas_fonte": "real",
          "realizadas": 15,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 13,
          "clid_pct": 27.7
        },
        "this_month": {
          "gasto": 768.27,
          "conversas": 4,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 486,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 6,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": 0.0,
          "teto_conversa": 0.0,
          "custo_conversa": 192.07,
          "folga": null,
          "iniciadas": 10,
          "iniciadas_fonte": "real",
          "realizadas": 4,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 1,
          "clid_pct": 10.0
        },
        "last_month": {
          "gasto": 1790.62,
          "conversas": 14,
          "conversas_fonte": "real",
          "leads": 6,
          "cliques": 1851,
          "vendas": 1,
          "faturamento": 43040.0,
          "consultas": 4,
          "ticket": 43040.0,
          "custo_venda": 1790.62,
          "lucro": 41249.38,
          "margem_pct": 95.8,
          "roas_conta": 24.04,
          "consultas_por_venda": 4.0,
          "taxa_conversao_pct": 25.0,
          "teto_conversa": 3074.29,
          "custo_conversa": 127.9,
          "folga": 24.04,
          "iniciadas": 56,
          "iniciadas_fonte": "real",
          "realizadas": 14,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 18,
          "clid_pct": 32.1
        },
        "maximum": {
          "gasto": 44301.94,
          "conversas": 23,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 80318,
          "vendas": 6,
          "faturamento": 175424.0,
          "consultas": 22,
          "ticket": 29237.33,
          "custo_venda": 7383.66,
          "lucro": 131122.06,
          "margem_pct": 74.7,
          "roas_conta": 3.96,
          "consultas_por_venda": 3.67,
          "taxa_conversao_pct": 27.3,
          "teto_conversa": 525.49,
          "custo_conversa": 132.7,
          "folga": 3.96,
          "gasto_janela": 3052.19,
          "iniciadas": 89,
          "iniciadas_fonte": "real",
          "realizadas": 23,
          "realizadas_fonte": "real",
          "janela_desde": "2026-06-19",
          "com_clid": 22,
          "clid_pct": 24.7
        }
      },
      "captura": {
        "desde": "2026-06-19",
        "contatos": 89,
        "com_clid": 22,
        "clid_pct": 24.7
      }
    },
    {
      "client": "Bruna Susanne",
      "label": "Bruna Susanne | Revisional",
      "currency": "BRL",
      "consulta_label": "Análise",
      "receita_esperada": true,
      "vendas_dia": {
        "2026-07-08": {
          "c": 0,
          "v": 6,
          "f": 9000.0,
          "p": {
            "Juros": {
              "v": 6,
              "f": 9000.0
            }
          }
        },
        "2026-07-17": {
          "c": 0,
          "v": 9,
          "f": 13500.0,
          "p": {
            "Juros": {
              "v": 9,
              "f": 13500.0
            }
          }
        },
        "2026-07-09": {
          "c": 0,
          "v": 10,
          "f": 15000.0,
          "p": {
            "Juros": {
              "v": 10,
              "f": 15000.0
            }
          }
        },
        "2026-07-07": {
          "c": 0,
          "v": 1,
          "f": 1500.0,
          "p": {
            "Juros": {
              "v": 1,
              "f": 1500.0
            }
          }
        },
        "2026-07-10": {
          "c": 0,
          "v": 11,
          "f": 16500.0,
          "p": {
            "Juros": {
              "v": 11,
              "f": 16500.0
            }
          }
        }
      },
      "periods": {
        "today": {
          "gasto": 31.34,
          "conversas": 6,
          "conversas_fonte": "real",
          "leads": 1,
          "cliques": 12,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 5.22,
          "folga": null,
          "iniciadas": 8,
          "iniciadas_fonte": "real",
          "realizadas": 6,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 8,
          "clid_pct": 100.0,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 10.02,
              "cliques": 8,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 6,
              "realizadas": 5,
              "conversas_fonte": "texto",
              "custo_conversa": 2.01,
              "gasto_janela": 10.05
            },
            {
              "nome": "Aéreo",
              "gasto": 21.32,
              "cliques": 4,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 2,
              "realizadas": 1,
              "conversas_fonte": "texto",
              "custo_conversa": 21.44,
              "gasto_janela": 21.44
            }
          ]
        },
        "yesterday": {
          "gasto": 81.93,
          "conversas": 3,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 36,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 27.31,
          "folga": null,
          "iniciadas": 5,
          "iniciadas_fonte": "real",
          "realizadas": 3,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 3,
          "clid_pct": 60.0,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 28.73,
              "cliques": 20,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 4,
              "realizadas": 3,
              "conversas_fonte": "texto",
              "custo_conversa": 9.58,
              "gasto_janela": 28.73
            },
            {
              "nome": "Aéreo",
              "gasto": 53.2,
              "cliques": 16,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null
            }
          ]
        },
        "last_7d": {
          "gasto": 560.39,
          "conversas": 50,
          "conversas_fonte": "real",
          "leads": 14,
          "cliques": 197,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 11.21,
          "folga": null,
          "iniciadas": 85,
          "iniciadas_fonte": "real",
          "realizadas": 50,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 76,
          "clid_pct": 89.4,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 217.72,
              "cliques": 131,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 72,
              "realizadas": 43,
              "conversas_fonte": "texto",
              "custo_conversa": 5.06,
              "gasto_janela": 217.72
            },
            {
              "nome": "Aéreo",
              "gasto": 342.67,
              "cliques": 66,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 8,
              "realizadas": 6,
              "conversas_fonte": "texto",
              "custo_conversa": 57.11,
              "gasto_janela": 342.67
            },
            {
              "nome": "Não classificado",
              "gasto": 0.0,
              "cliques": 0,
              "vendas": 0,
              "faturamento": 0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "resto": true,
              "iniciadas": 5,
              "realizadas": 1,
              "conversas_fonte": "texto"
            }
          ]
        },
        "last_14d": {
          "gasto": 1112.65,
          "conversas": 76,
          "conversas_fonte": "real",
          "leads": 14,
          "cliques": 1082,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 14.64,
          "folga": null,
          "iniciadas": 138,
          "iniciadas_fonte": "real",
          "realizadas": 76,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 118,
          "clid_pct": 85.5,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 424.1,
              "cliques": 932,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 92,
              "realizadas": 57,
              "conversas_fonte": "texto",
              "custo_conversa": 7.44,
              "gasto_janela": 424.1
            },
            {
              "nome": "Aéreo",
              "gasto": 688.55,
              "cliques": 150,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 28,
              "realizadas": 15,
              "conversas_fonte": "texto",
              "custo_conversa": 45.9,
              "gasto_janela": 688.55
            },
            {
              "nome": "Não classificado",
              "gasto": 0.0,
              "cliques": 0,
              "vendas": 0,
              "faturamento": 0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "resto": true,
              "iniciadas": 18,
              "realizadas": 4,
              "conversas_fonte": "texto"
            }
          ]
        },
        "last_30d": {
          "gasto": 2249.54,
          "conversas": 102,
          "conversas_fonte": "real",
          "leads": 19,
          "cliques": 1647,
          "vendas": 9,
          "faturamento": 13500.0,
          "consultas": 0,
          "ticket": 1500.0,
          "custo_venda": 249.95,
          "lucro": 11250.46,
          "margem_pct": 83.3,
          "roas_conta": 6.0,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 98.1,
          "custo_conversa": 16.35,
          "folga": 6.0,
          "gasto_janela": 1667.34,
          "iniciadas": 187,
          "iniciadas_fonte": "real",
          "realizadas": 102,
          "realizadas_fonte": "real",
          "janela_desde": "2026-07-23",
          "com_clid": 139,
          "clid_pct": 74.3,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 910.58,
              "cliques": 1088,
              "vendas": 9,
              "faturamento": 13500.0,
              "custo_venda": 101.18,
              "cliques_por_venda": 120.89,
              "iniciadas": 106,
              "realizadas": 69,
              "conversas_fonte": "texto",
              "custo_conversa": 9.03,
              "gasto_janela": 622.86
            },
            {
              "nome": "Aéreo",
              "gasto": 1338.96,
              "cliques": 559,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 35,
              "realizadas": 21,
              "conversas_fonte": "texto",
              "custo_conversa": 49.74,
              "gasto_janela": 1044.48
            },
            {
              "nome": "Não classificado",
              "gasto": 0.0,
              "cliques": 0,
              "vendas": 0,
              "faturamento": 0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "resto": true,
              "iniciadas": 46,
              "realizadas": 12,
              "conversas_fonte": "texto"
            }
          ]
        },
        "this_month": {
          "gasto": 1020.67,
          "conversas": 77,
          "conversas_fonte": "real",
          "leads": 15,
          "cliques": 1056,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 13.26,
          "folga": null,
          "iniciadas": 134,
          "iniciadas_fonte": "real",
          "realizadas": 77,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 116,
          "clid_pct": 86.6,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 387.06,
              "cliques": 920,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 96,
              "realizadas": 60,
              "conversas_fonte": "texto",
              "custo_conversa": 6.45,
              "gasto_janela": 387.09
            },
            {
              "nome": "Aéreo",
              "gasto": 633.61,
              "cliques": 136,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 30,
              "realizadas": 16,
              "conversas_fonte": "texto",
              "custo_conversa": 39.61,
              "gasto_janela": 633.73
            },
            {
              "nome": "Não classificado",
              "gasto": 0.0,
              "cliques": 0,
              "vendas": 0,
              "faturamento": 0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "resto": true,
              "iniciadas": 8,
              "realizadas": 1,
              "conversas_fonte": "texto"
            }
          ]
        },
        "last_month": {
          "gasto": 2221.51,
          "conversas": 31,
          "conversas_fonte": "real",
          "leads": 5,
          "cliques": 2336,
          "vendas": 37,
          "faturamento": 55500.0,
          "consultas": 0,
          "ticket": 1500.0,
          "custo_venda": 60.04,
          "lucro": 53278.49,
          "margem_pct": 96.0,
          "roas_conta": 24.98,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 546.31,
          "custo_conversa": 21.87,
          "folga": 24.98,
          "gasto_janela": 678.01,
          "iniciadas": 61,
          "iniciadas_fonte": "real",
          "realizadas": 31,
          "realizadas_fonte": "real",
          "janela_desde": "2026-07-23",
          "com_clid": 31,
          "clid_pct": 50.8,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 917.17,
              "cliques": 336,
              "vendas": 37,
              "faturamento": 55500.0,
              "custo_venda": 24.79,
              "cliques_por_venda": 9.08,
              "iniciadas": 16,
              "realizadas": 14,
              "conversas_fonte": "texto",
              "custo_conversa": 17.56,
              "gasto_janela": 245.82
            },
            {
              "nome": "Aéreo",
              "gasto": 1304.34,
              "cliques": 2000,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 7,
              "realizadas": 6,
              "conversas_fonte": "texto",
              "custo_conversa": 72.03,
              "gasto_janela": 432.19
            },
            {
              "nome": "Não classificado",
              "gasto": 0.0,
              "cliques": 0,
              "vendas": 0,
              "faturamento": 0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "resto": true,
              "iniciadas": 38,
              "realizadas": 11,
              "conversas_fonte": "texto"
            }
          ]
        },
        "maximum": {
          "gasto": 5236.68,
          "conversas": 108,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 6009,
          "vendas": 37,
          "faturamento": 55500.0,
          "consultas": 0,
          "ticket": 1500.0,
          "custo_venda": 141.53,
          "lucro": 50263.32,
          "margem_pct": 90.6,
          "roas_conta": 10.6,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 166.74,
          "custo_conversa": 15.73,
          "folga": 10.6,
          "gasto_janela": 1698.83,
          "iniciadas": 195,
          "iniciadas_fonte": "real",
          "realizadas": 108,
          "realizadas_fonte": "real",
          "janela_desde": "2026-07-23",
          "com_clid": 147,
          "clid_pct": 75.4,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 1565.06,
              "cliques": 1317,
              "vendas": 37,
              "faturamento": 55500.0,
              "custo_venda": 42.3,
              "cliques_por_venda": 35.59,
              "iniciadas": 112,
              "realizadas": 74,
              "conversas_fonte": "texto",
              "custo_conversa": 8.55,
              "gasto_janela": 632.91
            },
            {
              "nome": "Aéreo",
              "gasto": 1998.14,
              "cliques": 2422,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 37,
              "realizadas": 22,
              "conversas_fonte": "texto",
              "custo_conversa": 48.45,
              "gasto_janela": 1065.92
            },
            {
              "nome": "Não classificado",
              "gasto": 1673.48,
              "cliques": 2270,
              "vendas": 0,
              "faturamento": 0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "resto": true,
              "iniciadas": 46,
              "realizadas": 12,
              "conversas_fonte": "texto"
            }
          ]
        }
      },
      "captura": {
        "desde": "2026-07-23",
        "contatos": 195,
        "com_clid": 147,
        "clid_pct": 75.4
      },
      "frentes_cfg": [
        {
          "nome": "Juros",
          "campanhas": "juros",
          "canal": "site"
        },
        {
          "nome": "Aéreo",
          "campanhas": "a[ée]re",
          "canal": "whatsapp"
        }
      ]
    },
    {
      "client": "Silva & Co.",
      "label": "Silva & Co. (agência)",
      "currency": "BRL",
      "consulta_label": null,
      "receita_esperada": false,
      "vendas_dia": {},
      "periods": {
        "today": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "yesterday": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_7d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_14d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_30d": {
          "gasto": 43.92,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 36,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "this_month": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_month": {
          "gasto": 43.92,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 36,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "maximum": {
          "gasto": 43.92,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 36,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        }
      }
    },
    {
      "client": "Silva & Co. [02]",
      "label": "Silva & Co. [02] (infoprodutos)",
      "currency": "BRL",
      "consulta_label": null,
      "receita_esperada": false,
      "vendas_dia": {},
      "periods": {
        "today": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "yesterday": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_7d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_14d": {
          "gasto": 162.59,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 168,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_30d": {
          "gasto": 162.59,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 168,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "this_month": {
          "gasto": 100.09,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 36,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_month": {
          "gasto": 62.5,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 132,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "maximum": {
          "gasto": 162.59,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 168,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        }
      }
    }
  ]
};
