window.PAINEL_DATA = {
  "gerado_em": "2026-08-20T20:51:52+00:00",
  "periods": [
    "today",
    "yesterday",
    "last_7d",
    "last_14d",
    "last_30d",
    "this_month",
    "last_month",
    "maximum"
  ],
  "marcos": [
    {
      "cliente": "Bruna Susanne",
      "data": "2026-08-02",
      "titulo": "juros: ler SEMPRE em janela de 7 ou 28 dias",
      "efeito": "Medido nos mesmos R$ 917 de julho: janela de 1 dia mostra 1 venda (R$ 1.500), 7 dias mostra 6 (R$ 9.247), 28 dias mostra 7 (R$ 15.247). Só 1 das 7 vendas fecha em 24h do clique — o ciclo do revisional é longo. O número que aparece por padrão SUBCONTA a linha de juros. Ao relatar venda de juros, declarar a janela."
    },
    {
      "cliente": "Bruna Susanne",
      "data": "2026-07-21",
      "titulo": "Dualhook (coexistência do WhatsApp) entrou no ar",
      "efeito": "Só a partir daqui a Meta e o nosso webhook enxergam as mensagens trocadas. Antes desta data, conversa realizada e profundidade não eram ZERO — eram CEGAS. NÃO comparar leads/conversas antes × depois: a diferença é de medição, não de desempenho. Vale também para julgar criativo: quem rodou antes de 21/07 pode ter gerado conversa e venda sem registro (ex.: 'Quanto da parcela abate a dívida')."
    }
  ],
  "nota": "faturamento = caixa do cliente (não atribuído ≤7d); Bruna = receita esperada em caso de ganho; INICIADAS = quem começou a conversa (webhook onde cobre, senão Meta); REALIZADAS = trocou ≥N msgs (nosso webhook), na janela coberta — 'sem captura' antes do webhook ligar.",
  "accounts": [
    {
      "client": "Paola Bones",
      "label": "Estúdio Paola Bones",
      "currency": "BRL",
      "consulta_label": null,
      "receita_esperada": false,
      "vendas_dia": {},
      "periods": {
        "today": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "yesterday": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_7d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_14d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_30d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "this_month": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_month": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "maximum": {
          "gasto": 32716.46,
          "conversas": 1590,
          "conversas_fonte": "meta",
          "leads": 281,
          "cliques": 18797,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 20.58,
          "folga": null,
          "iniciadas": 1590,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        }
      }
    },
    {
      "client": "Marcelle Lima",
      "label": "Marcelle Lima | Esteticista",
      "currency": "BRL",
      "consulta_label": null,
      "receita_esperada": false,
      "vendas_dia": {
        "2026-08-12": {
          "c": 0,
          "v": 1,
          "f": 220.0
        },
        "2026-08-08": {
          "c": 0,
          "v": 2,
          "f": 373.0
        },
        "2026-08-07": {
          "c": 0,
          "v": 1,
          "f": 92.0
        },
        "2026-08-06": {
          "c": 0,
          "v": 2,
          "f": 440.0
        },
        "2026-08-03": {
          "c": 0,
          "v": 20,
          "f": 4765.5
        },
        "2026-08-15": {
          "c": 0,
          "v": 1,
          "f": 220.0
        }
      },
      "periods": {
        "today": {
          "gasto": 23.8,
          "conversas": 1,
          "conversas_fonte": "real",
          "leads": 3,
          "cliques": 7,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 23.8,
          "folga": null,
          "iniciadas": 2,
          "iniciadas_fonte": "real",
          "realizadas": 1,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 0,
          "clid_pct": 0.0
        },
        "yesterday": {
          "gasto": 38.42,
          "conversas": 0,
          "conversas_fonte": "real",
          "leads": 5,
          "cliques": 15,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 1,
          "iniciadas_fonte": "real",
          "realizadas": 0,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 0,
          "clid_pct": 0.0
        },
        "last_7d": {
          "gasto": 291.99,
          "conversas": 6,
          "conversas_fonte": "real",
          "leads": 19,
          "cliques": 108,
          "vendas": 1,
          "faturamento": 220.0,
          "consultas": 0,
          "ticket": 220.0,
          "custo_venda": 291.99,
          "lucro": -71.99,
          "margem_pct": -32.7,
          "roas_conta": 0.75,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 36.67,
          "custo_conversa": 48.66,
          "folga": 0.75,
          "iniciadas": 13,
          "iniciadas_fonte": "real",
          "realizadas": 6,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 3,
          "clid_pct": 23.1
        },
        "last_14d": {
          "gasto": 514.93,
          "conversas": 14,
          "conversas_fonte": "real",
          "leads": 22,
          "cliques": 172,
          "vendas": 7,
          "faturamento": 1345.0,
          "consultas": 0,
          "ticket": 192.14,
          "custo_venda": 73.56,
          "lucro": 830.07,
          "margem_pct": 61.7,
          "roas_conta": 2.61,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 96.07,
          "custo_conversa": 36.78,
          "folga": 2.61,
          "iniciadas": 24,
          "iniciadas_fonte": "real",
          "realizadas": 14,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 6,
          "clid_pct": 25.0
        },
        "last_30d": {
          "gasto": 1010.9,
          "conversas": 40,
          "conversas_fonte": "real",
          "leads": 54,
          "cliques": 279,
          "vendas": 27,
          "faturamento": 6110.5,
          "consultas": 0,
          "ticket": 226.31,
          "custo_venda": 37.44,
          "lucro": 5099.6,
          "margem_pct": 83.5,
          "roas_conta": 6.04,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 152.76,
          "custo_conversa": 25.27,
          "folga": 6.05,
          "iniciadas": 63,
          "iniciadas_fonte": "real",
          "realizadas": 40,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 18,
          "clid_pct": 28.6
        },
        "this_month": {
          "gasto": 538.73,
          "conversas": 17,
          "conversas_fonte": "real",
          "leads": 25,
          "cliques": 179,
          "vendas": 27,
          "faturamento": 6110.5,
          "consultas": 0,
          "ticket": 226.31,
          "custo_venda": 19.95,
          "lucro": 5571.77,
          "margem_pct": 91.2,
          "roas_conta": 11.34,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 359.44,
          "custo_conversa": 31.69,
          "folga": 11.34,
          "iniciadas": 28,
          "iniciadas_fonte": "real",
          "realizadas": 17,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 6,
          "clid_pct": 21.4
        },
        "last_month": {
          "gasto": 1045.29,
          "conversas": 45,
          "conversas_fonte": "real",
          "leads": 55,
          "cliques": 543,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 23.23,
          "folga": null,
          "iniciadas": 80,
          "iniciadas_fonte": "real",
          "realizadas": 45,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 36,
          "clid_pct": 45.0
        },
        "maximum": {
          "gasto": 12945.53,
          "conversas": 112,
          "conversas_fonte": "real",
          "leads": 371,
          "cliques": 7957,
          "vendas": 27,
          "faturamento": 6110.5,
          "consultas": 0,
          "ticket": 226.31,
          "custo_venda": 479.46,
          "lucro": -6835.03,
          "margem_pct": -111.9,
          "roas_conta": 0.47,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 11.76,
          "custo_conversa": 25.03,
          "folga": 0.47,
          "gasto_janela": 2803.35,
          "iniciadas": 188,
          "iniciadas_fonte": "real",
          "realizadas": 112,
          "realizadas_fonte": "real",
          "janela_desde": "2026-06-05",
          "com_clid": 88,
          "clid_pct": 46.8
        }
      },
      "captura": {
        "desde": "2026-06-05",
        "contatos": 188,
        "com_clid": 88,
        "clid_pct": 46.8
      }
    },
    {
      "client": "Sofia Scherer",
      "label": "Sofia Scherer | Biomédica",
      "currency": "BRL",
      "consulta_label": "Avaliação",
      "receita_esperada": false,
      "vendas_dia": {
        "2026-05-30": {
          "c": 0,
          "v": 2,
          "f": 3940.0
        },
        "2026-07-13": {
          "c": 4,
          "v": 0,
          "f": 0.0
        },
        "2026-07-23": {
          "c": 2,
          "v": 0,
          "f": 0.0
        },
        "2026-07-30": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-08-01": {
          "c": 0,
          "v": 1,
          "f": 4590.0
        },
        "2026-07-31": {
          "c": 0,
          "v": 2,
          "f": 2500.0
        }
      },
      "periods": {
        "today": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "real",
          "realizadas": 0,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 0,
          "clid_pct": null
        },
        "yesterday": {
          "gasto": 0,
          "conversas": 1,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 0.0,
          "folga": null,
          "iniciadas": 1,
          "iniciadas_fonte": "real",
          "realizadas": 1,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 0,
          "clid_pct": 0.0
        },
        "last_7d": {
          "gasto": 70.7,
          "conversas": 3,
          "conversas_fonte": "real",
          "leads": 1,
          "cliques": 9,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 23.57,
          "folga": null,
          "iniciadas": 6,
          "iniciadas_fonte": "real",
          "realizadas": 3,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 1,
          "clid_pct": 16.7
        },
        "last_14d": {
          "gasto": 331.17,
          "conversas": 6,
          "conversas_fonte": "real",
          "leads": 2,
          "cliques": 80,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 55.2,
          "folga": null,
          "iniciadas": 13,
          "iniciadas_fonte": "real",
          "realizadas": 6,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 2,
          "clid_pct": 15.4
        },
        "last_30d": {
          "gasto": 1097.86,
          "conversas": 18,
          "conversas_fonte": "real",
          "leads": 4,
          "cliques": 543,
          "vendas": 3,
          "faturamento": 7090.0,
          "consultas": 3,
          "ticket": 2363.33,
          "custo_venda": 365.95,
          "lucro": 5992.14,
          "margem_pct": 84.5,
          "roas_conta": 6.46,
          "consultas_por_venda": 1.0,
          "taxa_conversao_pct": 100.0,
          "teto_conversa": 393.89,
          "custo_conversa": 60.99,
          "folga": 6.46,
          "iniciadas": 33,
          "iniciadas_fonte": "real",
          "realizadas": 18,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 4,
          "clid_pct": 12.1
        },
        "this_month": {
          "gasto": 569.66,
          "conversas": 8,
          "conversas_fonte": "real",
          "leads": 2,
          "cliques": 218,
          "vendas": 1,
          "faturamento": 4590.0,
          "consultas": 0,
          "ticket": 4590.0,
          "custo_venda": 569.66,
          "lucro": 4020.34,
          "margem_pct": 87.6,
          "roas_conta": 8.06,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 573.75,
          "custo_conversa": 71.21,
          "folga": 8.06,
          "iniciadas": 18,
          "iniciadas_fonte": "real",
          "realizadas": 8,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 2,
          "clid_pct": 11.1
        },
        "last_month": {
          "gasto": 1162.73,
          "conversas": 41,
          "conversas_fonte": "real",
          "leads": 23,
          "cliques": 658,
          "vendas": 2,
          "faturamento": 2500.0,
          "consultas": 7,
          "ticket": 1250.0,
          "custo_venda": 581.37,
          "lucro": 1337.27,
          "margem_pct": 53.5,
          "roas_conta": 2.15,
          "consultas_por_venda": 3.5,
          "taxa_conversao_pct": 28.6,
          "teto_conversa": 56.2,
          "custo_conversa": 26.14,
          "folga": 2.15,
          "gasto_janela": 1071.77,
          "iniciadas": 64,
          "iniciadas_fonte": "real",
          "realizadas": 41,
          "realizadas_fonte": "real",
          "janela_desde": "2026-07-04",
          "com_clid": 20,
          "clid_pct": 31.2
        },
        "maximum": {
          "gasto": 7586.8,
          "conversas": 49,
          "conversas_fonte": "real",
          "leads": 40,
          "cliques": 10682,
          "vendas": 5,
          "faturamento": 11030.0,
          "consultas": 7,
          "ticket": 2206.0,
          "custo_venda": 1517.36,
          "lucro": 3443.2,
          "margem_pct": 31.2,
          "roas_conta": 1.45,
          "consultas_por_venda": 1.4,
          "taxa_conversao_pct": 71.4,
          "teto_conversa": 48.57,
          "custo_conversa": 33.5,
          "folga": 1.45,
          "gasto_janela": 1641.43,
          "iniciadas": 82,
          "iniciadas_fonte": "real",
          "realizadas": 49,
          "realizadas_fonte": "real",
          "janela_desde": "2026-07-04",
          "com_clid": 22,
          "clid_pct": 26.8
        }
      },
      "captura": {
        "desde": "2026-07-04",
        "contatos": 82,
        "com_clid": 22,
        "clid_pct": 26.8
      }
    },
    {
      "client": "Studio NL",
      "label": "Natalia Lazzarotto Arq.",
      "currency": "BRL",
      "consulta_label": "Reunião",
      "receita_esperada": false,
      "vendas_dia": {
        "2026-04-22": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-04-21": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-04-14": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-04-06": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-03-24": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-05-06": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-02-25": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-05-11": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-05-15": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-05-30": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-06-11": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-06-09": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-06-04": {
          "c": 0,
          "v": 1,
          "f": 15000.0
        },
        "2025-11-01": {
          "c": 0,
          "v": 1,
          "f": 22000.0
        },
        "2026-01-01": {
          "c": 0,
          "v": 2,
          "f": 70200.0
        },
        "2026-03-01": {
          "c": 0,
          "v": 1,
          "f": 25184.0
        },
        "2026-07-01": {
          "c": 2,
          "v": 0,
          "f": 0.0
        },
        "2026-07-06": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-08-19": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-08-07": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-08-04": {
          "c": 2,
          "v": 0,
          "f": 0.0
        },
        "2026-08-06": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-08-03": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-08-05": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-07-24": {
          "c": 0,
          "v": 1,
          "f": 43040.0
        },
        "2026-07-08": {
          "c": 1,
          "v": 0,
          "f": 0.0
        }
      },
      "periods": {
        "today": {
          "gasto": 43.2,
          "conversas": 1,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 16,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 43.2,
          "folga": null,
          "iniciadas": 1,
          "iniciadas_fonte": "real",
          "realizadas": 1,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 1,
          "clid_pct": 100.0
        },
        "yesterday": {
          "gasto": 76.0,
          "conversas": 1,
          "conversas_fonte": "real",
          "leads": 1,
          "cliques": 42,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 1,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": 0.0,
          "teto_conversa": 0.0,
          "custo_conversa": 76.0,
          "folga": null,
          "iniciadas": 3,
          "iniciadas_fonte": "real",
          "realizadas": 1,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 1,
          "clid_pct": 33.3
        },
        "last_7d": {
          "gasto": 423.16,
          "conversas": 3,
          "conversas_fonte": "real",
          "leads": 1,
          "cliques": 280,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 1,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": 0.0,
          "teto_conversa": 0.0,
          "custo_conversa": 141.05,
          "folga": null,
          "iniciadas": 7,
          "iniciadas_fonte": "real",
          "realizadas": 3,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 2,
          "clid_pct": 28.6
        },
        "last_14d": {
          "gasto": 839.9,
          "conversas": 5,
          "conversas_fonte": "real",
          "leads": 1,
          "cliques": 555,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 3,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": 0.0,
          "teto_conversa": 0.0,
          "custo_conversa": 167.98,
          "folga": null,
          "iniciadas": 14,
          "iniciadas_fonte": "real",
          "realizadas": 5,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 3,
          "clid_pct": 21.4
        },
        "last_30d": {
          "gasto": 1835.65,
          "conversas": 15,
          "conversas_fonte": "real",
          "leads": 3,
          "cliques": 1299,
          "vendas": 1,
          "faturamento": 43040.0,
          "consultas": 7,
          "ticket": 43040.0,
          "custo_venda": 1835.65,
          "lucro": 41204.35,
          "margem_pct": 95.7,
          "roas_conta": 23.45,
          "consultas_por_venda": 7.0,
          "taxa_conversao_pct": 14.3,
          "teto_conversa": 2869.33,
          "custo_conversa": 122.38,
          "folga": 23.45,
          "iniciadas": 41,
          "iniciadas_fonte": "real",
          "realizadas": 15,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 8,
          "clid_pct": 19.5
        },
        "this_month": {
          "gasto": 1201.92,
          "conversas": 8,
          "conversas_fonte": "real",
          "leads": 1,
          "cliques": 764,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 7,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": 0.0,
          "teto_conversa": 0.0,
          "custo_conversa": 150.24,
          "folga": null,
          "iniciadas": 18,
          "iniciadas_fonte": "real",
          "realizadas": 8,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 4,
          "clid_pct": 22.2
        },
        "last_month": {
          "gasto": 1790.62,
          "conversas": 14,
          "conversas_fonte": "real",
          "leads": 6,
          "cliques": 1851,
          "vendas": 1,
          "faturamento": 43040.0,
          "consultas": 4,
          "ticket": 43040.0,
          "custo_venda": 1790.62,
          "lucro": 41249.38,
          "margem_pct": 95.8,
          "roas_conta": 24.04,
          "consultas_por_venda": 4.0,
          "taxa_conversao_pct": 25.0,
          "teto_conversa": 3074.29,
          "custo_conversa": 127.9,
          "folga": 24.04,
          "iniciadas": 56,
          "iniciadas_fonte": "real",
          "realizadas": 14,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 18,
          "clid_pct": 32.1
        },
        "maximum": {
          "gasto": 44566.97,
          "conversas": 27,
          "conversas_fonte": "real",
          "leads": 138,
          "cliques": 80473,
          "vendas": 6,
          "faturamento": 175424.0,
          "consultas": 23,
          "ticket": 29237.33,
          "custo_venda": 7427.83,
          "lucro": 130857.03,
          "margem_pct": 74.6,
          "roas_conta": 3.94,
          "consultas_por_venda": 3.83,
          "taxa_conversao_pct": 26.1,
          "teto_conversa": 508.69,
          "custo_conversa": 129.11,
          "folga": 3.94,
          "gasto_janela": 3486.06,
          "iniciadas": 97,
          "iniciadas_fonte": "real",
          "realizadas": 27,
          "realizadas_fonte": "real",
          "janela_desde": "2026-06-19",
          "com_clid": 25,
          "clid_pct": 25.8
        }
      },
      "captura": {
        "desde": "2026-06-19",
        "contatos": 97,
        "com_clid": 25,
        "clid_pct": 25.8
      }
    },
    {
      "client": "Bruna Susanne",
      "label": "Bruna Susanne | Revisional",
      "currency": "BRL",
      "consulta_label": "Análise",
      "receita_esperada": true,
      "vendas_dia": {
        "2026-07-08": {
          "c": 0,
          "v": 6,
          "f": 9000.0,
          "p": {
            "Juros": {
              "v": 6,
              "f": 9000.0
            }
          }
        },
        "2026-07-17": {
          "c": 0,
          "v": 9,
          "f": 13500.0,
          "p": {
            "Juros": {
              "v": 9,
              "f": 13500.0
            }
          }
        },
        "2026-07-09": {
          "c": 0,
          "v": 10,
          "f": 15000.0,
          "p": {
            "Juros": {
              "v": 10,
              "f": 15000.0
            }
          }
        },
        "2026-07-07": {
          "c": 0,
          "v": 1,
          "f": 1500.0,
          "p": {
            "Juros": {
              "v": 1,
              "f": 1500.0
            }
          }
        },
        "2026-07-10": {
          "c": 0,
          "v": 11,
          "f": 16500.0,
          "p": {
            "Juros": {
              "v": 11,
              "f": 16500.0
            }
          }
        }
      },
      "periods": {
        "today": {
          "gasto": 60.94,
          "conversas": 4,
          "conversas_fonte": "real",
          "leads": 12,
          "cliques": 15,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 15.23,
          "folga": null,
          "iniciadas": 7,
          "iniciadas_fonte": "real",
          "realizadas": 4,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 7,
          "clid_pct": 100.0,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 18.41,
              "cliques": 9,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 5,
              "realizadas": 3,
              "conversas_fonte": "texto",
              "custo_conversa": 6.14,
              "gasto_janela": 18.41
            },
            {
              "nome": "Aéreo",
              "gasto": 42.53,
              "cliques": 6,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 2,
              "realizadas": 1,
              "conversas_fonte": "texto",
              "custo_conversa": 42.53,
              "gasto_janela": 42.53
            }
          ]
        },
        "yesterday": {
          "gasto": 94.18,
          "conversas": 8,
          "conversas_fonte": "real",
          "leads": 0,
          "cliques": 24,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 11.77,
          "folga": null,
          "iniciadas": 14,
          "iniciadas_fonte": "real",
          "realizadas": 8,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 14,
          "clid_pct": 100.0,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 31.6,
              "cliques": 17,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 11,
              "realizadas": 7,
              "conversas_fonte": "texto",
              "custo_conversa": 4.51,
              "gasto_janela": 31.6
            },
            {
              "nome": "Aéreo",
              "gasto": 62.58,
              "cliques": 7,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 3,
              "realizadas": 1,
              "conversas_fonte": "texto",
              "custo_conversa": 62.58,
              "gasto_janela": 62.58
            }
          ]
        },
        "last_7d": {
          "gasto": 553.61,
          "conversas": 43,
          "conversas_fonte": "real",
          "leads": 5,
          "cliques": 133,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 12.87,
          "folga": null,
          "iniciadas": 75,
          "iniciadas_fonte": "real",
          "realizadas": 43,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 68,
          "clid_pct": 90.7,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 210.5,
              "cliques": 99,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 63,
              "realizadas": 37,
              "conversas_fonte": "texto",
              "custo_conversa": 5.69,
              "gasto_janela": 210.5
            },
            {
              "nome": "Aéreo",
              "gasto": 343.11,
              "cliques": 34,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 10,
              "realizadas": 6,
              "conversas_fonte": "texto",
              "custo_conversa": 57.19,
              "gasto_janela": 343.11
            }
          ]
        },
        "last_14d": {
          "gasto": 1114.0,
          "conversas": 93,
          "conversas_fonte": "real",
          "leads": 19,
          "cliques": 330,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 11.98,
          "folga": null,
          "iniciadas": 160,
          "iniciadas_fonte": "real",
          "realizadas": 93,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 145,
          "clid_pct": 90.6,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 428.22,
              "cliques": 230,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 135,
              "realizadas": 80,
              "conversas_fonte": "texto",
              "custo_conversa": 5.35,
              "gasto_janela": 428.22
            },
            {
              "nome": "Aéreo",
              "gasto": 685.78,
              "cliques": 100,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 18,
              "realizadas": 12,
              "conversas_fonte": "texto",
              "custo_conversa": 57.15,
              "gasto_janela": 685.78
            },
            {
              "nome": "Não classificado",
              "gasto": 0.0,
              "cliques": 0,
              "vendas": 0,
              "faturamento": 0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "resto": true,
              "iniciadas": 7,
              "realizadas": 1,
              "conversas_fonte": "texto"
            }
          ]
        },
        "last_30d": {
          "gasto": 2365.37,
          "conversas": 145,
          "conversas_fonte": "real",
          "leads": 24,
          "cliques": 1337,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 15.32,
          "folga": null,
          "gasto_janela": 2220.95,
          "iniciadas": 262,
          "iniciadas_fonte": "real",
          "realizadas": 145,
          "realizadas_fonte": "real",
          "janela_desde": "2026-07-23",
          "com_clid": 208,
          "clid_pct": 79.4,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 906.67,
              "cliques": 1099,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 171,
              "realizadas": 108,
              "conversas_fonte": "texto",
              "custo_conversa": 7.72,
              "gasto_janela": 833.36
            },
            {
              "nome": "Aéreo",
              "gasto": 1458.7,
              "cliques": 238,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 45,
              "realizadas": 27,
              "conversas_fonte": "texto",
              "custo_conversa": 51.39,
              "gasto_janela": 1387.59
            },
            {
              "nome": "Não classificado",
              "gasto": 0.0,
              "cliques": 0,
              "vendas": 0,
              "faturamento": 0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "resto": true,
              "iniciadas": 46,
              "realizadas": 10,
              "conversas_fonte": "texto"
            }
          ]
        },
        "this_month": {
          "gasto": 1603.88,
          "conversas": 118,
          "conversas_fonte": "real",
          "leads": 31,
          "cliques": 1192,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 13.59,
          "folga": null,
          "iniciadas": 208,
          "iniciadas_fonte": "real",
          "realizadas": 118,
          "realizadas_fonte": "real",
          "janela_desde": null,
          "com_clid": 184,
          "clid_pct": 88.5,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 605.95,
              "cliques": 1020,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 158,
              "realizadas": 95,
              "conversas_fonte": "texto",
              "custo_conversa": 6.38,
              "gasto_janela": 605.95
            },
            {
              "nome": "Aéreo",
              "gasto": 997.93,
              "cliques": 172,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 40,
              "realizadas": 22,
              "conversas_fonte": "texto",
              "custo_conversa": 45.36,
              "gasto_janela": 997.93
            },
            {
              "nome": "Não classificado",
              "gasto": 0.0,
              "cliques": 0,
              "vendas": 0,
              "faturamento": 0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "resto": true,
              "iniciadas": 10,
              "realizadas": 1,
              "conversas_fonte": "texto"
            }
          ]
        },
        "last_month": {
          "gasto": 2221.51,
          "conversas": 31,
          "conversas_fonte": "real",
          "leads": 5,
          "cliques": 2336,
          "vendas": 37,
          "faturamento": 55500.0,
          "consultas": 0,
          "ticket": 1500.0,
          "custo_venda": 60.04,
          "lucro": 53278.49,
          "margem_pct": 96.0,
          "roas_conta": 24.98,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 546.31,
          "custo_conversa": 21.87,
          "folga": 24.98,
          "gasto_janela": 678.01,
          "iniciadas": 61,
          "iniciadas_fonte": "real",
          "realizadas": 31,
          "realizadas_fonte": "real",
          "janela_desde": "2026-07-23",
          "com_clid": 31,
          "clid_pct": 50.8,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 917.17,
              "cliques": 336,
              "vendas": 37,
              "faturamento": 55500.0,
              "custo_venda": 24.79,
              "cliques_por_venda": 9.08,
              "iniciadas": 18,
              "realizadas": 16,
              "conversas_fonte": "texto",
              "custo_conversa": 15.36,
              "gasto_janela": 245.82
            },
            {
              "nome": "Aéreo",
              "gasto": 1304.34,
              "cliques": 2000,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 7,
              "realizadas": 6,
              "conversas_fonte": "texto",
              "custo_conversa": 72.03,
              "gasto_janela": 432.19
            },
            {
              "nome": "Não classificado",
              "gasto": 0.0,
              "cliques": 0,
              "vendas": 0,
              "faturamento": 0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "resto": true,
              "iniciadas": 36,
              "realizadas": 9,
              "conversas_fonte": "texto"
            }
          ]
        },
        "maximum": {
          "gasto": 5758.95,
          "conversas": 149,
          "conversas_fonte": "real",
          "leads": 24,
          "cliques": 6130,
          "vendas": 37,
          "faturamento": 55500.0,
          "consultas": 0,
          "ticket": 1500.0,
          "custo_venda": 155.65,
          "lucro": 49741.05,
          "margem_pct": 89.6,
          "roas_conta": 9.64,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 147.59,
          "custo_conversa": 15.31,
          "folga": 9.64,
          "gasto_janela": 2281.89,
          "iniciadas": 269,
          "iniciadas_fonte": "real",
          "realizadas": 149,
          "realizadas_fonte": "real",
          "janela_desde": "2026-07-23",
          "com_clid": 215,
          "clid_pct": 79.9,
          "frentes": [
            {
              "nome": "Juros",
              "gasto": 1890.02,
              "cliques": 2313,
              "vendas": 37,
              "faturamento": 55500.0,
              "custo_venda": 51.08,
              "cliques_por_venda": 62.51,
              "iniciadas": 176,
              "realizadas": 111,
              "conversas_fonte": "texto",
              "custo_conversa": 7.67,
              "gasto_janela": 851.77
            },
            {
              "nome": "Aéreo",
              "gasto": 2319.93,
              "cliques": 2452,
              "vendas": 0,
              "faturamento": 0.0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "iniciadas": 47,
              "realizadas": 28,
              "conversas_fonte": "texto",
              "custo_conversa": 51.08,
              "gasto_janela": 1430.12
            },
            {
              "nome": "Não classificado",
              "gasto": 1549.0,
              "cliques": 1365,
              "vendas": 0,
              "faturamento": 0,
              "custo_venda": null,
              "cliques_por_venda": null,
              "resto": true,
              "iniciadas": 46,
              "realizadas": 10,
              "conversas_fonte": "texto"
            }
          ]
        }
      },
      "captura": {
        "desde": "2026-07-23",
        "contatos": 269,
        "com_clid": 215,
        "clid_pct": 79.9
      },
      "frentes_cfg": [
        {
          "nome": "Juros",
          "campanhas": "juros",
          "canal": "site"
        },
        {
          "nome": "Aéreo",
          "campanhas": "a[ée]re",
          "canal": "whatsapp"
        }
      ]
    },
    {
      "client": "Silva & Co.",
      "label": "Silva & Co. (agência)",
      "currency": "BRL",
      "consulta_label": null,
      "receita_esperada": false,
      "vendas_dia": {},
      "periods": {
        "today": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "yesterday": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_7d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_14d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_30d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "this_month": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_month": {
          "gasto": 43.92,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 36,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "maximum": {
          "gasto": 43.92,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 36,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        }
      }
    },
    {
      "client": "Silva & Co. [02]",
      "label": "Silva & Co. [02] (infoprodutos)",
      "currency": "BRL",
      "consulta_label": null,
      "receita_esperada": false,
      "vendas_dia": {},
      "periods": {
        "today": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "yesterday": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_7d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_14d": {
          "gasto": 0,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_30d": {
          "gasto": 162.59,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 168,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "this_month": {
          "gasto": 100.09,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 36,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "last_month": {
          "gasto": 62.5,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 132,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        },
        "maximum": {
          "gasto": 162.59,
          "conversas": 0,
          "conversas_fonte": "meta",
          "leads": 0,
          "cliques": 168,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null,
          "iniciadas": 0,
          "iniciadas_fonte": "meta",
          "realizadas": null,
          "realizadas_fonte": "nenhuma",
          "janela_desde": null,
          "com_clid": null,
          "clid_pct": null
        }
      }
    }
  ]
};
