window.PAINEL_DATA = {
  "gerado_em": "2026-07-12T14:46:50+00:00",
  "periods": [
    "today",
    "yesterday",
    "last_7d",
    "last_14d",
    "last_30d",
    "this_month",
    "last_month",
    "maximum"
  ],
  "nota": "faturamento = caixa do cliente (não atribuído ≤7d); Bruna = receita esperada em caso de ganho; conversas = da Meta (proxy até o webhook real).",
  "accounts": [
    {
      "client": "Paola Bones",
      "label": "Estúdio Paola Bones",
      "currency": "BRL",
      "consulta_label": null,
      "receita_esperada": false,
      "vendas_dia": {},
      "periods": {
        "today": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "yesterday": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "last_7d": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "last_14d": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "last_30d": {
          "gasto": 1768.74,
          "conversas": 37,
          "leads": 14,
          "cliques": 1285,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 47.8,
          "folga": null
        },
        "this_month": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "last_month": {
          "gasto": 2376.22,
          "conversas": 52,
          "leads": 22,
          "cliques": 1580,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 45.7,
          "folga": null
        },
        "maximum": {
          "gasto": 32716.46,
          "conversas": 0,
          "leads": 0,
          "cliques": 18797,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        }
      }
    },
    {
      "client": "Marcelle Lima",
      "label": "Marcelle Lima | Esteticista",
      "currency": "BRL",
      "consulta_label": null,
      "receita_esperada": false,
      "vendas_dia": {},
      "periods": {
        "today": {
          "gasto": 8.72,
          "conversas": 0,
          "leads": 0,
          "cliques": 22,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "yesterday": {
          "gasto": 51.56,
          "conversas": 0,
          "leads": 0,
          "cliques": 101,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "last_7d": {
          "gasto": 124.3,
          "conversas": 3,
          "leads": 3,
          "cliques": 227,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 41.43,
          "folga": null
        },
        "last_14d": {
          "gasto": 294.19,
          "conversas": 17,
          "leads": 14,
          "cliques": 262,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 17.31,
          "folga": null
        },
        "last_30d": {
          "gasto": 1094.61,
          "conversas": 50,
          "leads": 41,
          "cliques": 380,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 21.89,
          "folga": null
        },
        "this_month": {
          "gasto": 177.82,
          "conversas": 6,
          "leads": 6,
          "cliques": 262,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 29.64,
          "folga": null
        },
        "last_month": {
          "gasto": 1250.4,
          "conversas": 61,
          "leads": 60,
          "cliques": 193,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 20.5,
          "folga": null
        },
        "maximum": {
          "gasto": 11563.13,
          "conversas": 542,
          "leads": 300,
          "cliques": 7504,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 21.33,
          "folga": null
        }
      }
    },
    {
      "client": "Sofia Scherer",
      "label": "Sofia Scherer | Biomédica",
      "currency": "BRL",
      "consulta_label": "Avaliação",
      "receita_esperada": false,
      "vendas_dia": {
        "2026-05-30": {
          "c": 0,
          "v": 2,
          "f": 3940.0
        }
      },
      "periods": {
        "today": {
          "gasto": 13.57,
          "conversas": 1,
          "leads": 1,
          "cliques": 5,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 13.57,
          "folga": null
        },
        "yesterday": {
          "gasto": 16.39,
          "conversas": 0,
          "leads": 0,
          "cliques": 17,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "last_7d": {
          "gasto": 209.67,
          "conversas": 9,
          "leads": 7,
          "cliques": 127,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 23.3,
          "folga": null
        },
        "last_14d": {
          "gasto": 423.41,
          "conversas": 19,
          "leads": 14,
          "cliques": 279,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 22.28,
          "folga": null
        },
        "last_30d": {
          "gasto": 1390.7,
          "conversas": 63,
          "leads": 15,
          "cliques": 672,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 22.07,
          "folga": null
        },
        "this_month": {
          "gasto": 336.88,
          "conversas": 15,
          "leads": 13,
          "cliques": 216,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 22.46,
          "folga": null
        },
        "last_month": {
          "gasto": 1672.55,
          "conversas": 76,
          "leads": 5,
          "cliques": 1204,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 22.01,
          "folga": null
        },
        "maximum": {
          "gasto": 6191.29,
          "conversas": 214,
          "leads": 28,
          "cliques": 10022,
          "vendas": 2,
          "faturamento": 3940.0,
          "consultas": 0,
          "ticket": 1970.0,
          "custo_venda": 3095.64,
          "lucro": -2251.29,
          "margem_pct": -57.1,
          "roas_conta": 0.64,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 18.41,
          "custo_conversa": 28.93,
          "folga": 0.64
        }
      }
    },
    {
      "client": "Studio NL",
      "label": "Natalia Lazzarotto Arq.",
      "currency": "BRL",
      "consulta_label": "Reunião",
      "receita_esperada": false,
      "vendas_dia": {
        "2026-04-22": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-04-21": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-04-14": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-04-06": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-03-24": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-05-06": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-02-25": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-05-11": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-05-15": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-05-30": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-06-11": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-06-09": {
          "c": 1,
          "v": 0,
          "f": 0.0
        },
        "2026-06-04": {
          "c": 0,
          "v": 1,
          "f": 15000.0
        },
        "2025-11-01": {
          "c": 0,
          "v": 1,
          "f": 22000.0
        },
        "2026-01-01": {
          "c": 0,
          "v": 2,
          "f": 70200.0
        },
        "2026-03-01": {
          "c": 0,
          "v": 1,
          "f": 25184.0
        },
        "2026-07-01": {
          "c": 2,
          "v": 0,
          "f": 0.0
        },
        "2026-07-06": {
          "c": 1,
          "v": 0,
          "f": 0.0
        }
      },
      "periods": {
        "today": {
          "gasto": 11.95,
          "conversas": 0,
          "leads": 0,
          "cliques": 9,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "yesterday": {
          "gasto": 42.94,
          "conversas": 1,
          "leads": 0,
          "cliques": 58,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 42.94,
          "folga": null
        },
        "last_7d": {
          "gasto": 348.4,
          "conversas": 4,
          "leads": 1,
          "cliques": 412,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 1,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": 0.0,
          "teto_conversa": 0.0,
          "custo_conversa": 87.1,
          "folga": null
        },
        "last_14d": {
          "gasto": 661.99,
          "conversas": 9,
          "leads": 6,
          "cliques": 816,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 3,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": 0.0,
          "teto_conversa": 0.0,
          "custo_conversa": 73.55,
          "folga": null
        },
        "last_30d": {
          "gasto": 1391.61,
          "conversas": 22,
          "leads": 8,
          "cliques": 2178,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 3,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": 0.0,
          "teto_conversa": 0.0,
          "custo_conversa": 63.25,
          "folga": null
        },
        "this_month": {
          "gasto": 548.94,
          "conversas": 6,
          "leads": 4,
          "cliques": 661,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 3,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": 0.0,
          "teto_conversa": 0.0,
          "custo_conversa": 91.49,
          "folga": null
        },
        "last_month": {
          "gasto": 1418.76,
          "conversas": 44,
          "leads": 5,
          "cliques": 2564,
          "vendas": 1,
          "faturamento": 15000.0,
          "consultas": 2,
          "ticket": 15000.0,
          "custo_venda": 1418.76,
          "lucro": 13581.24,
          "margem_pct": 90.5,
          "roas_conta": 10.57,
          "consultas_por_venda": 2.0,
          "taxa_conversao_pct": 50.0,
          "teto_conversa": 340.91,
          "custo_conversa": 32.24,
          "folga": 10.57
        },
        "maximum": {
          "gasto": 42456.94,
          "conversas": 0,
          "leads": 0,
          "cliques": 78776,
          "vendas": 5,
          "faturamento": 132384.0,
          "consultas": 15,
          "ticket": 26476.8,
          "custo_venda": 8491.39,
          "lucro": 89927.06,
          "margem_pct": 67.9,
          "roas_conta": 3.12,
          "consultas_por_venda": 3.0,
          "taxa_conversao_pct": 33.3,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        }
      }
    },
    {
      "client": "Bruna Susanne",
      "label": "Bruna Susanne | Revisional",
      "currency": "BRL",
      "consulta_label": "Análise",
      "receita_esperada": true,
      "vendas_dia": {
        "2026-07-08": {
          "c": 0,
          "v": 6,
          "f": 9000.0
        },
        "2026-07-07": {
          "c": 0,
          "v": 1,
          "f": 1500.0
        },
        "2026-07-09": {
          "c": 0,
          "v": 10,
          "f": 15000.0
        }
      },
      "periods": {
        "today": {
          "gasto": 39.53,
          "conversas": 0,
          "leads": 0,
          "cliques": 38,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "yesterday": {
          "gasto": 61.97,
          "conversas": 1,
          "leads": 0,
          "cliques": 69,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 61.97,
          "folga": null
        },
        "last_7d": {
          "gasto": 475.29,
          "conversas": 6,
          "leads": 0,
          "cliques": 577,
          "vendas": 17,
          "faturamento": 25500.0,
          "consultas": 0,
          "ticket": 1500.0,
          "custo_venda": 27.96,
          "lucro": 25024.71,
          "margem_pct": 98.1,
          "roas_conta": 53.65,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 4250.0,
          "custo_conversa": 79.22,
          "folga": 53.65
        },
        "last_14d": {
          "gasto": 943.18,
          "conversas": 8,
          "leads": 0,
          "cliques": 1830,
          "vendas": 17,
          "faturamento": 25500.0,
          "consultas": 0,
          "ticket": 1500.0,
          "custo_venda": 55.48,
          "lucro": 24556.82,
          "margem_pct": 96.3,
          "roas_conta": 27.04,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 3187.5,
          "custo_conversa": 117.9,
          "folga": 27.04
        },
        "last_30d": {
          "gasto": 1221.48,
          "conversas": 10,
          "leads": 0,
          "cliques": 2771,
          "vendas": 17,
          "faturamento": 25500.0,
          "consultas": 0,
          "ticket": 1500.0,
          "custo_venda": 71.85,
          "lucro": 24278.52,
          "margem_pct": 95.2,
          "roas_conta": 20.88,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 2550.0,
          "custo_conversa": 122.15,
          "folga": 20.88
        },
        "this_month": {
          "gasto": 815.51,
          "conversas": 7,
          "leads": 0,
          "cliques": 1557,
          "vendas": 17,
          "faturamento": 25500.0,
          "consultas": 0,
          "ticket": 1500.0,
          "custo_venda": 47.97,
          "lucro": 24684.49,
          "margem_pct": 96.8,
          "roas_conta": 31.27,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": 3642.86,
          "custo_conversa": 116.5,
          "folga": 31.27
        },
        "last_month": {
          "gasto": 445.5,
          "conversas": 3,
          "leads": 0,
          "cliques": 1252,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": 0.0,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": 0.0,
          "custo_conversa": 148.5,
          "folga": null
        },
        "maximum": {
          "gasto": 2810.01,
          "conversas": 0,
          "leads": 0,
          "cliques": 4174,
          "vendas": 17,
          "faturamento": 25500.0,
          "consultas": 0,
          "ticket": 1500.0,
          "custo_venda": 165.29,
          "lucro": 22689.99,
          "margem_pct": 89.0,
          "roas_conta": 9.07,
          "consultas_por_venda": 0.0,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        }
      }
    },
    {
      "client": "Silva & Co.",
      "label": "Silva & Co. (agência)",
      "currency": "BRL",
      "consulta_label": null,
      "receita_esperada": false,
      "vendas_dia": {},
      "periods": {
        "today": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "yesterday": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "last_7d": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "last_14d": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "last_30d": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "this_month": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "last_month": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        },
        "maximum": {
          "gasto": 0,
          "conversas": 0,
          "leads": 0,
          "cliques": 0,
          "vendas": 0,
          "faturamento": 0,
          "consultas": 0,
          "ticket": null,
          "custo_venda": null,
          "lucro": null,
          "margem_pct": null,
          "roas_conta": null,
          "consultas_por_venda": null,
          "taxa_conversao_pct": null,
          "teto_conversa": null,
          "custo_conversa": null,
          "folga": null
        }
      }
    }
  ]
};
